/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as ResultadoRouteImport } from './routes/resultado'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PedidosIntegradosRouteImport } from './routes/pedidos-integrados'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as FluxoCaixaRouteImport } from './routes/fluxo-caixa'
import { Route as ContasPagarRouteImport } from './routes/contas-pagar'
import { Route as ConexoesRouteImport } from './routes/conexoes'
import { Route as CmvRouteImport } from './routes/cmv'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicShopeeCallbackRouteImport } from './routes/api/public/shopee/callback'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadoRoute = ResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIntegradosRoute = PedidosIntegradosRouteImport.update({
  id: '/pedidos-integrados',
  path: '/pedidos-integrados',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoCaixaRoute = FluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasPagarRoute = ContasPagarRouteImport.update({
  id: '/contas-pagar',
  path: '/contas-pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConexoesRoute = ConexoesRouteImport.update({
  id: '/conexoes',
  path: '/conexoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CmvRoute = CmvRouteImport.update({
  id: '/cmv',
  path: '/cmv',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopeeCallbackRoute = ApiPublicShopeeCallbackRouteImport.update({
  id: '/api/public/shopee/callback',
  path: '/api/public/shopee/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/carteira': typeof CarteiraRoute
  '/cmv': typeof CmvRoute
  '/conexoes': typeof ConexoesRoute
  '/contas-pagar': typeof ContasPagarRoute
  '/fluxo-caixa': typeof FluxoCaixaRoute
  '/pedidos': typeof PedidosRoute
  '/pedidos-integrados': typeof PedidosIntegradosRoute
  '/produtos': typeof ProdutosRoute
  '/resultado': typeof ResultadoRoute
  '/vendas': typeof VendasRoute
  '/api/public/shopee/callback': typeof ApiPublicShopeeCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/carteira': typeof CarteiraRoute
  '/cmv': typeof CmvRoute
  '/conexoes': typeof ConexoesRoute
  '/contas-pagar': typeof ContasPagarRoute
  '/fluxo-caixa': typeof FluxoCaixaRoute
  '/pedidos': typeof PedidosRoute
  '/pedidos-integrados': typeof PedidosIntegradosRoute
  '/produtos': typeof ProdutosRoute
  '/resultado': typeof ResultadoRoute
  '/vendas': typeof VendasRoute
  '/api/public/shopee/callback': typeof ApiPublicShopeeCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/carteira': typeof CarteiraRoute
  '/cmv': typeof CmvRoute
  '/conexoes': typeof ConexoesRoute
  '/contas-pagar': typeof ContasPagarRoute
  '/fluxo-caixa': typeof FluxoCaixaRoute
  '/pedidos': typeof PedidosRoute
  '/pedidos-integrados': typeof PedidosIntegradosRoute
  '/produtos': typeof ProdutosRoute
  '/resultado': typeof ResultadoRoute
  '/vendas': typeof VendasRoute
  '/api/public/shopee/callback': typeof ApiPublicShopeeCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/carteira'
    | '/cmv'
    | '/conexoes'
    | '/contas-pagar'
    | '/fluxo-caixa'
    | '/pedidos'
    | '/pedidos-integrados'
    | '/produtos'
    | '/resultado'
    | '/vendas'
    | '/api/public/shopee/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads'
    | '/carteira'
    | '/cmv'
    | '/conexoes'
    | '/contas-pagar'
    | '/fluxo-caixa'
    | '/pedidos'
    | '/pedidos-integrados'
    | '/produtos'
    | '/resultado'
    | '/vendas'
    | '/api/public/shopee/callback'
  id:
    | '__root__'
    | '/'
    | '/ads'
    | '/carteira'
    | '/cmv'
    | '/conexoes'
    | '/contas-pagar'
    | '/fluxo-caixa'
    | '/pedidos'
    | '/pedidos-integrados'
    | '/produtos'
    | '/resultado'
    | '/vendas'
    | '/api/public/shopee/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRoute
  CarteiraRoute: typeof CarteiraRoute
  CmvRoute: typeof CmvRoute
  ConexoesRoute: typeof ConexoesRoute
  ContasPagarRoute: typeof ContasPagarRoute
  FluxoCaixaRoute: typeof FluxoCaixaRoute
  PedidosRoute: typeof PedidosRoute
  PedidosIntegradosRoute: typeof PedidosIntegradosRoute
  ProdutosRoute: typeof ProdutosRoute
  ResultadoRoute: typeof ResultadoRoute
  VendasRoute: typeof VendasRoute
  ApiPublicShopeeCallbackRoute: typeof ApiPublicShopeeCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultado': {
      id: '/resultado'
      path: '/resultado'
      fullPath: '/resultado'
      preLoaderRoute: typeof ResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos-integrados': {
      id: '/pedidos-integrados'
      path: '/pedidos-integrados'
      fullPath: '/pedidos-integrados'
      preLoaderRoute: typeof PedidosIntegradosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo-caixa': {
      id: '/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/fluxo-caixa'
      preLoaderRoute: typeof FluxoCaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas-pagar': {
      id: '/contas-pagar'
      path: '/contas-pagar'
      fullPath: '/contas-pagar'
      preLoaderRoute: typeof ContasPagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conexoes': {
      id: '/conexoes'
      path: '/conexoes'
      fullPath: '/conexoes'
      preLoaderRoute: typeof ConexoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cmv': {
      id: '/cmv'
      path: '/cmv'
      fullPath: '/cmv'
      preLoaderRoute: typeof CmvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopee/callback': {
      id: '/api/public/shopee/callback'
      path: '/api/public/shopee/callback'
      fullPath: '/api/public/shopee/callback'
      preLoaderRoute: typeof ApiPublicShopeeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRoute,
  CarteiraRoute: CarteiraRoute,
  CmvRoute: CmvRoute,
  ConexoesRoute: ConexoesRoute,
  ContasPagarRoute: ContasPagarRoute,
  FluxoCaixaRoute: FluxoCaixaRoute,
  PedidosRoute: PedidosRoute,
  PedidosIntegradosRoute: PedidosIntegradosRoute,
  ProdutosRoute: ProdutosRoute,
  ResultadoRoute: ResultadoRoute,
  VendasRoute: VendasRoute,
  ApiPublicShopeeCallbackRoute: ApiPublicShopeeCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
